### ISSUE TITLE
File Group Header - Dark Theme - Hard to Read

### ISSUE THREAD

**Issue by marbaugh** [AndrewRathbun/DirectoryOpus-DFIRConfig#2]
When importing the Dark Theme, the File/Fold Group Header blue color is hard to read.
Recommend changing to something easier on the eyes.

Settings-->Preferences-->Colors and Fonts--->File and Folder Colors --> File group header, Text Color.

I made it lime green and increased the font size a few points (to 11) under, Settings-->Preferences-->Colors and Fonts-->Fonts-->File display groups, Font Size.

**Comment by AndrewRathbun** [comment]
Fixed in V3 - https://github.com/AndrewRathbun/DirectoryOpus-DFIRConfig/releases/tag/V3
