### ISSUE TITLE
Network Drives set to 'Prevent Loading'

### ISSUE THREAD

**Issue by marbaugh** [AndrewRathbun/DirectoryOpus-DFIRConfig#3]
In the config, the Network Drives set to 'Prevent Loading'.

![Image Pasted at 2022-2-10 09-47](https://user-images.githubusercontent.com/6455490/153434045-be84a86a-083a-4efc-898f-fb9896e41c47.png)

Maybe add this to the documentation?

**Comment by AndrewRathbun** [comment]
I have these already in the documentation but they must've not made it to production, for some reason. I'll fix this in V3.

**Comment by AndrewRathbun** [comment]
Fixed in https://github.com/AndrewRathbun/DirectoryOpus-DFIRConfig/releases/tag/V3
